sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t danielmocan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielmocan/react-test npm test

after_success:
  - docker build -t danielmocan/multi-client ./client
  - docker build -t danielmocan/multi-nginx ./nginx
  - docker build -t danielmocan/multi-server ./server
  - docker build -t danielmocan/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push danielmocan/multi-client
  - docker push danielmocan/multi-nginx
  - docker push danielmocan/multi-server
  - docker push danielmocan/multi-worker